branch-defaults:
  develop:
    environment: systers-vms-dev
environment-defaults:
  systers-vms-dev:
    branch: null
    repository: null
global:
  application_name: systers-vms
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.7.1
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
